version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - /${HOME}/data/postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: always

  app:
    container_name: api_gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  pgadmin:
    container_name: nest-pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '8080:80'
    depends_on:
      - db
    restart: always

networks:
  postgres:
    driver: bridge